// 第51回衆議院議員総選挙 比例代表当選者データ
// スクレイピング元: Wikipedia 各比例ブロックページ

export interface ProportionalWinner {
  rank: number;
  name: string;
  party: string;
  block: string;
  is_overlap: boolean;
  overlap_district: string | null;
  recovery_rate: string | null;
  photo: string | null;
}

export const PROPORTIONAL_WINNERS: ProportionalWinner[] = [
  { rank: 1, name: "伊東良孝", party: "自由民主党", block: "北海道", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Yoshitaka_It%C5%8D%2C_Minister_of_State_for_Special_Missions_%28cropped_2%29.jpg/330px-Yoshitaka_It%C5%8D%2C_Minister_of_State_for_Special_Missions_%28cropped_2%29.jpg" },
  { rank: 2, name: "佐藤英道", party: "中道改革連合", block: "北海道", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/4/43/20211111sato_hidemichi.jpg" },
  { rank: 3, name: "渡辺孝一", party: "自由民主党", block: "北海道", is_overlap: true, overlap_district: "北海道10区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/5/54/Watanabe_Kouichi_%282019%29.png" },
  { rank: 4, name: "村木汀", party: "自由民主党", block: "北海道", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Nagisa_Muraki_cropped_1_20260220shu_san_honkaigi5.jpg" },
  { rank: 5, name: "浮島智子", party: "中道改革連合", block: "北海道", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 6, name: "吉田有理", party: "自由民主党", block: "北海道", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 7, name: "臼木秀剛", party: "国民民主党", block: "北海道", is_overlap: true, overlap_district: "北海道1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Hidetake_Usuki_20241118.jpg" },
  { rank: 8, name: "山岡達丸", party: "中道改革連合", block: "北海道", is_overlap: true, overlap_district: "北海道9区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Tatsumaru-Yamaoka-MJP-20230704.jpg/330px-Tatsumaru-Yamaoka-MJP-20230704.jpg" },
  { rank: 1, name: "江渡聡徳", party: "自由民主党", block: "東北", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Akinori_Eto.jpg/330px-Akinori_Eto.jpg" },
  { rank: 2, name: "庄子賢一", party: "中道改革連合", block: "東北", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Kenichi_Shoji_2024.jpg" },
  { rank: 3, name: "御法川信英", party: "自由民主党", block: "東北", is_overlap: true, overlap_district: "秋田3区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Nobuhide_Minorikawa_on_August_6%2C_2024.jpg/330px-Nobuhide_Minorikawa_on_August_6%2C_2024.jpg" },
  { rank: 4, name: "米内紘正", party: "自由民主党", block: "東北", is_overlap: true, overlap_district: "岩手1区", recovery_rate: null, photo: null },
  { rank: 5, name: "有田芳生", party: "中道改革連合", block: "東北", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Yoshifu_Arita_2024-10-14%281%29_%28cropped%29.jpg/330px-Yoshifu_Arita_2024-10-14%281%29_%28cropped%29.jpg" },
  { rank: 6, name: "伊藤信太郎", party: "自由民主党", block: "東北", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/1/10/Shintar%C5%8D_It%C5%8D.2023.jpg" },
  { rank: 7, name: "佐々木真琴", party: "国民民主党", block: "東北", is_overlap: true, overlap_district: "岩手2区", recovery_rate: null, photo: null },
  { rank: 8, name: "菅家一郎", party: "自由民主党", block: "東北", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Kanke_ichiro.jpg" },
  { rank: 9, name: "和田政宗", party: "参政党", block: "東北", is_overlap: true, overlap_district: "宮城2区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/0/04/Masamune_Wada_20130328.jpg" },
  { rank: 10, name: "金子恵美", party: "中道改革連合", block: "東北", is_overlap: true, overlap_district: "福島1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Kaneko_megumi.jpg" },
  { rank: 11, name: "秋葉賢也", party: "自由民主党", block: "東北", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Kenya_Akiba_20190911.jpg/330px-Kenya_Akiba_20190911.jpg" },
  { rank: 12, name: "林拓海", party: "チームみらい", block: "東北", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 1, name: "簗和生", party: "自由民主党", block: "北関東", is_overlap: true, overlap_district: "栃木3区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/8/80/98_yana_kazuo.jpg" },
  { rank: 2, name: "石井啓一", party: "中道改革連合", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Keiichi_Ishii_20230315teigen_komei2.jpg/330px-Keiichi_Ishii_20230315teigen_komei2.jpg" },
  { rank: 3, name: "永岡桂子", party: "自由民主党", block: "北関東", is_overlap: true, overlap_district: "茨城7区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Keiko_Nagaoka_2023_%28cropped%29.jpg/330px-Keiko_Nagaoka_2023_%28cropped%29.jpg" },
  { rank: 4, name: "鈴木拓海", party: "自由民主党", block: "北関東", is_overlap: true, overlap_district: "茨城5区", recovery_rate: null, photo: null },
  { rank: 5, name: "橋本幹彦", party: "国民民主党", block: "北関東", is_overlap: true, overlap_district: "埼玉13区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Hashimoto_mikihiko20241207.jpg/330px-Hashimoto_mikihiko20241207.jpg" },
  { rank: 6, name: "輿水恵一", party: "中道改革連合", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/9/96/Keiichi_Koshimizu_20241003.jpg" },
  { rank: 7, name: "中根一幸", party: "自由民主党", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/7/74/Kazuyuki_Nakane.jpg" },
  { rank: 8, name: "豊田真由子", party: "参政党", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Mayuko_Toyota_cropped_1_Mayuko_Toyota_201510.jpg/330px-Mayuko_Toyota_cropped_1_Mayuko_Toyota_201510.jpg" },
  { rank: 9, name: "武藤かず子", party: "チームみらい", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 10, name: "西條昌良", party: "自由民主党", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 11, name: "福重隆浩", party: "中道改革連合", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 12, name: "石川昭政", party: "自由民主党", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Akimasa_Ishikawa.jpg" },
  { rank: 13, name: "柏倉祐司", party: "日本維新の会", block: "北関東", is_overlap: true, overlap_district: "栃木1区", recovery_rate: null, photo: null },
  { rank: 14, name: "尾身朝子", party: "自由民主党", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Asako_Omi_20170912.jpg/330px-Asako_Omi_20170912.jpg" },
  { rank: 15, name: "鈴木義弘", party: "国民民主党", block: "北関東", is_overlap: true, overlap_district: "埼玉14区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Yoshihiro_Suzuki_2025-05-05_%28cropped%29.jpg/330px-Yoshihiro_Suzuki_2025-05-05_%28cropped%29.jpg" },
  { rank: 16, name: "大島敦", party: "中道改革連合", block: "北関東", is_overlap: true, overlap_district: "埼玉6区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/0/02/Oshima_Atsushi.jpg" },
  { rank: 17, name: "前川恵", party: "自由民主党", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 18, name: "塩川鉄也", party: "日本共産党", block: "北関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Shiokawatetsuya202108JCP.jpg/330px-Shiokawatetsuya202108JCP.jpg" },
  { rank: 19, name: "青木ひとみ", party: "参政党", block: "北関東", is_overlap: true, overlap_district: "群馬4区", recovery_rate: null, photo: null },
  { rank: 1, name: "長野春信", party: "自由民主党", block: "南関東", is_overlap: true, overlap_district: "千葉14区", recovery_rate: null, photo: null },
  { rank: 2, name: "角田秀穂", party: "中道改革連合", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Hideho_Tsunoda_20170926.jpg" },
  { rank: 3, name: "伊藤聡", party: "自由民主党", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 4, name: "文月涼", party: "自由民主党", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 5, name: "深作ヘスス", party: "国民民主党", block: "南関東", is_overlap: true, overlap_district: "神奈川19区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Fukasaku_Jes%C3%BAs_2025-02-08%282%29_%28cropped%29.jpg/330px-Fukasaku_Jes%C3%BAs_2025-02-08%282%29_%28cropped%29.jpg" },
  { rank: 6, name: "沼崎満子", party: "中道改革連合", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 7, name: "河合道雄", party: "チームみらい", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 8, name: "岩崎比菜", party: "自由民主党", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Hina_Iwasaki.png/330px-Hina_Iwasaki.png" },
  { rank: 9, name: "中谷めぐみ", party: "参政党", block: "南関東", is_overlap: true, overlap_district: "千葉13区", recovery_rate: null, photo: null },
  { rank: 10, name: "原田直樹", party: "中道改革連合", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: "ー", photo: null },
  { rank: 11, name: "金村龍那", party: "日本維新の会", block: "南関東", is_overlap: true, overlap_district: "神奈川10区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ryuna_Kanamura_2022-6-26%28cropped%29.jpg/330px-Ryuna_Kanamura_2022-6-26%28cropped%29.jpg" },
  { rank: 12, name: "西岡義高", party: "国民民主党", block: "南関東", is_overlap: true, overlap_district: "神奈川18区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Yoshitaka_Nishioka_2025-02-08%281%29_%28cropped%29.jpg/330px-Yoshitaka_Nishioka_2025-02-08%281%29_%28cropped%29.jpg" },
  { rank: 13, name: "笠浩史", party: "中道改革連合", block: "南関東", is_overlap: true, overlap_district: "神奈川9区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/2/29/Hirofumi_Ryu.jpg" },
  { rank: 14, name: "山田瑛理", party: "チームみらい", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: "なし", photo: null },
  { rank: 15, name: "畑野君枝", party: "日本共産党", block: "南関東", is_overlap: false, overlap_district: null, recovery_rate: "なし", photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Kimie_Hatano_2024-10-26%282%29_%28cropped%29.jpg/330px-Kimie_Hatano_2024-10-26%282%29_%28cropped%29.jpg" },
  { rank: 16, name: "後藤祐一", party: "中道改革連合", block: "南関東", is_overlap: true, overlap_district: "神奈川16区", recovery_rate: null, photo: null },
  { rank: 17, name: "工藤聖子", party: "参政党", block: "南関東", is_overlap: true, overlap_district: "千葉4区", recovery_rate: null, photo: null },
  { rank: 18, name: "岡野純子", party: "国民民主党", block: "南関東", is_overlap: true, overlap_district: "千葉5区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Junko_Okano_2025-04-27%281%29_%28cropped%29.jpg/330px-Junko_Okano_2025-04-27%281%29_%28cropped%29.jpg" },
  { rank: 19, name: "早稲田夕季", party: "中道改革連合", block: "南関東", is_overlap: true, overlap_district: "神奈川4区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Yuki_Waseda_2022-2-7%283%29%28cropped%29.jpg/330px-Yuki_Waseda_2022-2-7%283%29%28cropped%29.jpg" },
  { rank: 20, name: "横田光弘", party: "日本維新の会", block: "南関東", is_overlap: true, overlap_district: "神奈川18区", recovery_rate: null, photo: null },
  { rank: 21, name: "小林修平", party: "チームみらい", block: "南関東", is_overlap: true, overlap_district: "千葉5区", recovery_rate: null, photo: null },
  { rank: 22, name: "田嶋要", party: "中道改革連合", block: "南関東", is_overlap: true, overlap_district: "千葉1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Tajima_Kaname.jpg/330px-Tajima_Kaname.jpg" },
  { rank: 1, name: "田中昌史", party: "自由民主党", block: "東京", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Masashi_Tanaka_20250418moushiire.jpg" },
  { rank: 2, name: "辻由布子", party: "自由民主党", block: "東京", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 3, name: "岡本三成", party: "中道改革連合", block: "東京", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Mitsunari_Okamoto_on_May_29%2C_2025_%28cropped%29.jpg/330px-Mitsunari_Okamoto_on_May_29%2C_2025_%28cropped%29.jpg" },
  { rank: 4, name: "高山聡史", party: "チームみらい", block: "東京", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/%E9%AB%98%E5%B1%B1%E8%81%A1%E5%8F%B2%EF%BC%882025%E5%B9%B410%E6%9C%8812%E6%97%A5%E3%83%BB%E7%B8%A6%E7%94%BB%E5%83%8F%EF%BC%89.jpg/330px-%E9%AB%98%E5%B1%B1%E8%81%A1%E5%8F%B2%EF%BC%882025%E5%B9%B410%E6%9C%8812%E6%97%A5%E3%83%BB%E7%B8%A6%E7%94%BB%E5%83%8F%EF%BC%89.jpg" },
  { rank: 5, name: "森原紀代子", party: "自由民主党", block: "東京", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 6, name: "森洋介", party: "国民民主党", block: "東京", is_overlap: true, overlap_district: "東京13区", recovery_rate: null, photo: null },
  { rank: 7, name: "河西宏一", party: "中道改革連合", block: "東京", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/K%C5%8Dichi_Kasai_2024-11-07.jpg/330px-K%C5%8Dichi_Kasai_2024-11-07.jpg" },
  { rank: 8, name: "峰島侑也", party: "チームみらい", block: "東京", is_overlap: true, overlap_district: "東京7区", recovery_rate: null, photo: null },
  { rank: 9, name: "吉川里奈", party: "参政党", block: "東京", is_overlap: true, overlap_district: "|東京1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/%E8%A1%97%E9%A0%AD%E6%BC%94%E8%AA%AC_%E5%90%89%E5%B7%9D%E3%82%8A%E3%81%AA%E2%91%A2.jpg/330px-%E8%A1%97%E9%A0%AD%E6%BC%94%E8%AA%AC_%E5%90%89%E5%B7%9D%E3%82%8A%E3%81%AA%E2%91%A2.jpg" },
  { rank: 10, name: "田村智子", party: "日本共産党", block: "東京", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Tomoko_Tamura_2024-10-26%284%29_%28cropped%29.jpg/330px-Tomoko_Tamura_2024-10-26%284%29_%28cropped%29.jpg" },
  { rank: 11, name: "阿部司", party: "日本維新の会", block: "東京", is_overlap: true, overlap_district: "東京12区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Tsukasa_Abe_cropped_1_20251111_ishin-teigen_1.jpg/330px-Tsukasa_Abe_cropped_1_20251111_ishin-teigen_1.jpg" },
  { rank: 12, name: "高沢一基", party: "国民民主党", block: "東京", is_overlap: true, overlap_district: "東京11区", recovery_rate: null, photo: null },
  { rank: 13, name: "大森江里子", party: "中道改革連合", block: "東京", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Centrist_Reform_Alliance_politicians_2026-01-25%2808%29_%28cropped%29.jpg/330px-Centrist_Reform_Alliance_politicians_2026-01-25%2808%29_%28cropped%29.jpg" },
  { rank: 14, name: "宇佐美登", party: "チームみらい", block: "東京", is_overlap: true, overlap_district: "東京26区", recovery_rate: null, photo: null },
  { rank: 15, name: "長妻昭", party: "中道改革連合", block: "東京", is_overlap: true, overlap_district: "東京27区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Akira_Nagatsuma_2024-10-19%282%29_%28cropped%29.jpg/330px-Akira_Nagatsuma_2024-10-19%282%29_%28cropped%29.jpg" },
  { rank: 16, name: "井戸まさえ", party: "国民民主党", block: "東京", is_overlap: true, overlap_district: "東京4区", recovery_rate: null, photo: null },
  { rank: 17, name: "落合貴之", party: "中道改革連合", block: "東京", is_overlap: true, overlap_district: "東京6区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/2025%E5%B9%B44%E6%9C%8815%E6%97%A5%E9%A3%9F%E6%96%99%E5%93%81%E3%81%AE%E6%B6%88%E8%B2%BB%E7%A8%8E%E3%82%BC%E3%83%AD%EF%BC%85%E3%82%92%E5%AE%9F%E7%8F%BE%E3%81%99%E3%82%8B%E4%BC%9A_%E8%90%BD%E5%90%88%E8%B2%B4%E4%B9%8B_%E8%A1%86%E8%AD%B0%E9%99%A2%E7%AC%AC%E4%BA%8C%E8%AD%B0%E5%93%A1%E4%BC%9A%E9%A4%A8_%28cropped%29.jpg/330px-2025%E5%B9%B44%E6%9C%8815%E6%97%A5%E9%A3%9F%E6%96%99%E5%93%81%E3%81%AE%E6%B6%88%E8%B2%BB%E7%A8%8E%E3%82%BC%E3%83%AD%EF%BC%85%E3%82%92%E5%AE%9F%E7%8F%BE%E3%81%99%E3%82%8B%E4%BC%9A_%E8%90%BD%E5%90%88%E8%B2%B4%E4%B9%8B_%E8%A1%86%E8%AD%B0%E9%99%A2%E7%AC%AC%E4%BA%8C%E8%AD%B0%E5%93%A1%E4%BC%9A%E9%A4%A8_%28cropped%29.jpg" },
  { rank: 18, name: "土橋章宏", party: "チームみらい", block: "東京", is_overlap: true, overlap_district: "東京2区", recovery_rate: null, photo: null },
  { rank: 19, name: "鈴木美香", party: "参政党", block: "東京", is_overlap: true, overlap_district: "|東京22区", recovery_rate: null, photo: null },
  { rank: 1, name: "田畑裕明", party: "自由民主党", block: "北陸信越", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/c/ce/20211006tabata_hiroaki2.jpg" },
  { rank: 2, name: "今洋佑", party: "自由民主党", block: "北陸信越", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 3, name: "中川宏昌", party: "中道改革連合", block: "北陸信越", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 4, name: "古井康介", party: "自由民主党", block: "北陸信越", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 5, name: "小竹凱", party: "国民民主党", block: "北陸信越", is_overlap: true, overlap_district: "石川1区", recovery_rate: null, photo: null },
  { rank: 6, name: "近藤和也", party: "中道改革連合", block: "北陸信越", is_overlap: true, overlap_district: "石川3区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Kazuya_Kondo_20200808_%28cropped%29.jpg" },
  { rank: 7, name: "川裕一郎", party: "参政党", block: "北陸信越", is_overlap: true, overlap_district: "石川1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/%E5%85%9A%E4%BB%A3%E8%A1%A8%E9%81%B8%E4%BC%9A%E8%A6%8B_%E5%B7%9D%E8%A3%95%E4%B8%80%E9%83%8E.jpg/330px-%E5%85%9A%E4%BB%A3%E8%A1%A8%E9%81%B8%E4%BC%9A%E8%A6%8B_%E5%B7%9D%E8%A3%95%E4%B8%80%E9%83%8E.jpg" },
  { rank: 8, name: "若狹清史", party: "日本維新の会", block: "北陸信越", is_overlap: true, overlap_district: "長野1区", recovery_rate: null, photo: null },
  { rank: 9, name: "西村智奈美", party: "中道改革連合", block: "北陸信越", is_overlap: true, overlap_district: "新潟1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Chinami_Nishimura_20230911.jpg/330px-Chinami_Nishimura_20230911.jpg" },
  { rank: 10, name: "菊田真紀子", party: "中道改革連合", block: "北陸信越", is_overlap: true, overlap_district: "新潟2区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Makiko_Kikuta_20240623enzetsu.png" },
  { rank: 1, name: "山本左近", party: "自由民主党", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/6/69/Sakon_Yamamoto_20220818.jpg" },
  { rank: 2, name: "鈴木淳司", party: "自由民主党", block: "東海", is_overlap: true, overlap_district: "愛知7区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Junji_Suzuki_20180925.jpg" },
  { rank: 3, name: "中川康洋", party: "中道改革連合", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/3/37/20211111nakagawa_yasuhiro.jpg" },
  { rank: 4, name: "熊田裕通", party: "自由民主党", block: "東海", is_overlap: true, overlap_district: "愛知1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Hiromichi_Kumada.jpg" },
  { rank: 5, name: "田中健", party: "国民民主党", block: "東海", is_overlap: true, overlap_district: "静岡4区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Ken_Tanaka_20221020.jpg/330px-Ken_Tanaka_20221020.jpg" },
  { rank: 6, name: "辻秀樹", party: "自由民主党", block: "東海", is_overlap: true, overlap_district: "愛知2区", recovery_rate: null, photo: null },
  { rank: 7, name: "西園勝秀", party: "中道改革連合", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/%E8%A1%86%E8%AD%B0%E9%99%A2%E8%AD%B0%E5%93%A1%E3%83%BB%E8%A5%BF%E5%9C%92_%E5%8B%9D%E7%A7%80%EF%BC%88%E3%81%AB%E3%81%97%E3%81%9E%E3%81%AE_%E3%81%8B%E3%81%A4%E3%81%B2%E3%81%A7%EF%BC%89.jpg/330px-%E8%A1%86%E8%AD%B0%E9%99%A2%E8%AD%B0%E5%93%A1%E3%83%BB%E8%A5%BF%E5%9C%92_%E5%8B%9D%E7%A7%80%EF%BC%88%E3%81%AB%E3%81%97%E3%81%9E%E3%81%AE_%E3%81%8B%E3%81%A4%E3%81%B2%E3%81%A7%EF%BC%89.jpg" },
  { rank: 8, name: "渡辺藍理", party: "参政党", block: "東海", is_overlap: true, overlap_district: "愛知5区", recovery_rate: null, photo: null },
  { rank: 9, name: "藤澤忠盛", party: "自由民主党", block: "東海", is_overlap: true, overlap_district: "愛知11区", recovery_rate: null, photo: null },
  { rank: 10, name: "須田英太郎", party: "チームみらい", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/%E9%A0%88%E7%94%B0%E3%81%88%E3%81%84%E3%81%9F%E3%82%8D%E3%81%86_7%E6%9C%8819%E6%97%A5.png/330px-%E9%A0%88%E7%94%B0%E3%81%88%E3%81%84%E3%81%9F%E3%82%8D%E3%81%86_7%E6%9C%8819%E6%97%A5.png" },
  { rank: 11, name: "細田健一", party: "自由民主党", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/c/cf/20211006hosoda_kenichi.jpg" },
  { rank: 12, name: "福田徹", party: "国民民主党", block: "東海", is_overlap: true, overlap_district: "愛知16区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/2025%E5%B9%B411%E6%9C%8815%E6%97%A5_%E5%90%8D%E5%8F%A4%E5%B1%8B%E9%A7%85%E5%89%8D%E3%81%A7%E8%A1%97%E9%A0%AD%E6%BC%94%E8%AA%AC%E3%82%92%E8%A1%8C%E3%81%86%E7%A6%8F%E7%94%B0%E5%BE%B9.jpg/330px-2025%E5%B9%B411%E6%9C%8815%E6%97%A5_%E5%90%8D%E5%8F%A4%E5%B1%8B%E9%A7%85%E5%89%8D%E3%81%A7%E8%A1%97%E9%A0%AD%E6%BC%94%E8%AA%AC%E3%82%92%E8%A1%8C%E3%81%86%E7%A6%8F%E7%94%B0%E5%BE%B9.jpg" },
  { rank: 13, name: "関健一郎", party: "日本維新の会", block: "東海", is_overlap: true, overlap_district: "愛知15区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/%E9%96%A2%E5%81%A5%E4%B8%80%E9%83%8E.jpg/330px-%E9%96%A2%E5%81%A5%E4%B8%80%E9%83%8E.jpg" },
  { rank: 14, name: "犬飼明佳", party: "中道改革連合", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 15, name: "中川貴元", party: "自由民主党", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Takamoto_Nakagawa_20220812_%28original%29.jpg" },
  { rank: 16, name: "斉藤里恵", party: "自由民主党", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Rie_Saito_2019-07_at_Kobe_Sannomiya.jpg/330px-Rie_Saito_2019-07_at_Kobe_Sannomiya.jpg" },
  { rank: 17, name: "重徳和彦", party: "中道改革連合", block: "東海", is_overlap: true, overlap_district: "愛知12区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Kazuhiko_Shigetoku_%282014.03.23%29_2.jpg/330px-Kazuhiko_Shigetoku_%282014.03.23%29_2.jpg" },
  { rank: 18, name: "長田紘一郎", party: "自由民主党", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/%E8%A1%86%E8%AD%B0%E9%99%A2%E8%AD%B0%E5%93%A1_%E9%95%B7%E7%94%B0_%E7%B4%98%E4%B8%80%E9%83%8E_%E6%B0%8F_%EF%BC%92%EF%BC%90%E6%97%A5_%E8%A1%86%E8%AD%B0%E9%99%A2%E6%9C%AC%E4%BC%9A%E8%AD%B0%E5%A0%B4.jpg/330px-%E8%A1%86%E8%AD%B0%E9%99%A2%E8%AD%B0%E5%93%A1_%E9%95%B7%E7%94%B0_%E7%B4%98%E4%B8%80%E9%83%8E_%E6%B0%8F_%EF%BC%92%EF%BC%90%E6%97%A5_%E8%A1%86%E8%AD%B0%E9%99%A2%E6%9C%AC%E4%BC%9A%E8%AD%B0%E5%A0%B4.jpg" },
  { rank: 19, name: "野村美穂", party: "国民民主党", block: "東海", is_overlap: true, overlap_district: "岐阜2区", recovery_rate: null, photo: null },
  { rank: 20, name: "伊藤恵介", party: "参政党", block: "東海", is_overlap: true, overlap_district: "岐阜3区", recovery_rate: null, photo: null },
  { rank: 21, name: "世古万美子", party: "自由民主党", block: "東海", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 1, name: "小寺裕雄", party: "自由民主党", block: "近畿", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/20211006kotera_hiroo.jpg/330px-20211006kotera_hiroo.jpg" },
  { rank: 2, name: "原山大亮", party: "日本維新の会", block: "近畿", is_overlap: true, overlap_district: "奈良3区", recovery_rate: null, photo: null },
  { rank: 3, name: "石田真敏", party: "自由民主党", block: "近畿", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Masatoshi_Ishida_2024-12-23.jpg/330px-Masatoshi_Ishida_2024-12-23.jpg" },
  { rank: 4, name: "赤羽一嘉", party: "中道改革連合", block: "近畿", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Kazuyoshi_Akaba_20120521.jpg/330px-Kazuyoshi_Akaba_20120521.jpg" },
  { rank: 5, name: "伊東信久", party: "日本維新の会", block: "近畿", is_overlap: true, overlap_district: "大阪19区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Nobuhisa_It%C5%8D_cropped_1_20251204_shakaihoshou_3.jpg/330px-Nobuhisa_It%C5%8D_cropped_1_20251204_shakaihoshou_3.jpg" },
  { rank: 6, name: "繁本護", party: "自由民主党", block: "近畿", is_overlap: true, overlap_district: "京都3区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/a/ad/20211006shigemoto_mamoru.jpg" },
  { rank: 7, name: "市村浩一郎", party: "日本維新の会", block: "近畿", is_overlap: true, overlap_district: "兵庫6区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Koichiro_Ichimura_IMG_3732-1_20171014.jpg/330px-Koichiro_Ichimura_IMG_3732-1_20171014.jpg" },
  { rank: 8, name: "渡嘉敷奈緒美", party: "自由民主党", block: "近畿", is_overlap: true, overlap_district: "大阪7区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Naomi_Tokashiki_Jimin_IMG_5317_20130706.JPG/330px-Naomi_Tokashiki_Jimin_IMG_5317_20130706.JPG" },
  { rank: 9, name: "中野洋昌", party: "中道改革連合", block: "近畿", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/6/66/Hiromasa_Nakano_20241206.jpg" },
  { rank: 10, name: "河井昭成", party: "国民民主党", block: "近畿", is_overlap: true, overlap_district: "滋賀1区", recovery_rate: null, photo: null },
  { rank: 11, name: "石川勝", party: "参政党", block: "近畿", is_overlap: true, overlap_district: "大阪7区", recovery_rate: null, photo: null },
  { rank: 12, name: "宗清皇一", party: "自由民主党", block: "近畿", is_overlap: true, overlap_district: "大阪13区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/K%C5%8Dichi_Munekiyo_20150502.jpg/330px-K%C5%8Dichi_Munekiyo_20150502.jpg" },
  { rank: 13, name: "池畑浩太朗", party: "日本維新の会", block: "近畿", is_overlap: true, overlap_district: "兵庫12区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/6/65/K%C5%8Dtar%C5%8D_Ikehata_20250315.jpg" },
  { rank: 14, name: "辰巳孝太郎", party: "日本共産党", block: "近畿", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Kotaro_Tatsumi_2014.png/330px-Kotaro_Tatsumi_2014.png" },
  { rank: 15, name: "高麗啓一郎", party: "自由民主党", block: "近畿", is_overlap: true, overlap_district: "大阪8区", recovery_rate: null, photo: null },
  { rank: 16, name: "山本香苗", party: "中道改革連合", block: "近畿", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/1/13/Kanae_Yamamoto_20240530.jpg" },
  { rank: 17, name: "住吉寛紀", party: "日本維新の会", block: "近畿", is_overlap: true, overlap_district: "兵庫11区", recovery_rate: null, photo: null },
  { rank: 18, name: "中山泰秀", party: "自由民主党", block: "近畿", is_overlap: true, overlap_district: "大阪4区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Yasuhide_Nakayama.jpg" },
  { rank: 19, name: "三木圭恵", party: "日本維新の会", block: "近畿", is_overlap: true, overlap_district: "兵庫7区", recovery_rate: null, photo: null },
  { rank: 20, name: "島田智明", party: "自由民主党", block: "近畿", is_overlap: true, overlap_district: "大阪15区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Tomoaki_Shimada_3.jpg/330px-Tomoaki_Shimada_3.jpg" },
  { rank: 21, name: "伊佐進一", party: "中道改革連合", block: "近畿", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Shinichi_Isa_20161030.jpg/330px-Shinichi_Isa_20161030.jpg" },
  { rank: 22, name: "向山好一", party: "国民民主党", block: "近畿", is_overlap: true, overlap_district: "兵庫3区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Japanese_general_election_2012_Kouichi_Mukoyama_in_Motomachi_IMG_0074_20121209.JPG/330px-Japanese_general_election_2012_Kouichi_Mukoyama_in_Motomachi_IMG_0074_20121209.JPG" },
  { rank: 23, name: "東田淳平", party: "自由民主党", block: "近畿", is_overlap: true, overlap_district: "大阪9区", recovery_rate: null, photo: null },
  { rank: 24, name: "谷浩一郎", party: "参政党", block: "近畿", is_overlap: true, overlap_district: "兵庫6区", recovery_rate: null, photo: null },
  { rank: 25, name: "斎藤アレックス", party: "日本維新の会", block: "近畿", is_overlap: true, overlap_district: "滋賀1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Alexsaito.jpg/330px-Alexsaito.jpg" },
  { rank: 26, name: "藤田洋司", party: "自由民主党", block: "近畿", is_overlap: true, overlap_district: "京都2区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/2/21/Y%C5%8Dji_Fujita_cropped_1_20260220shu_san_honkaigi5.jpg" },
  { rank: 27, name: "一谷勇一郎", party: "日本維新の会", block: "近畿", is_overlap: true, overlap_district: "兵庫1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Gthumb.svg/330px-Gthumb.svg.png" },
  { rank: 28, name: "国重徹", party: "中道改革連合", block: "近畿", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/5/52/Toru_Kunishige.jpg" },
  { rank: 1, name: "寺田稔", party: "自由民主党", block: "中国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Terada_minoru.jpg" },
  { rank: 2, name: "平沼正二郎", party: "自由民主党", block: "中国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Sh%C5%8Djir%C5%8D_Hiranuma_2023.jpg/330px-Sh%C5%8Djir%C5%8D_Hiranuma_2023.jpg" },
  { rank: 3, name: "斉藤鉄夫", party: "中道改革連合", block: "中国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Tetsuo_Saito_20211004.jpg/330px-Tetsuo_Saito_20211004.jpg" },
  { rank: 4, name: "吉田真次", party: "自由民主党", block: "中国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Shinji_Yoshida_20251027_%28cropped%29.jpg/330px-Shinji_Yoshida_20251027_%28cropped%29.jpg" },
  { rank: 5, name: "阿部俊子", party: "自由民主党", block: "中国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Toshiko_Abe_20200604_%28cropped%29.jpg/330px-Toshiko_Abe_20200604_%28cropped%29.jpg" },
  { rank: 6, name: "平林晃", party: "中道改革連合", block: "中国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 7, name: "鍋島勢理", party: "国民民主党", block: "中国", is_overlap: true, overlap_district: "広島4区", recovery_rate: null, photo: null },
  { rank: 8, name: "俵田祐児", party: "自由民主党", block: "中国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 9, name: "島村薫", party: "参政党", block: "中国", is_overlap: true, overlap_district: "山口3区", recovery_rate: null, photo: null },
  { rank: 10, name: "喜多義典", party: "日本維新の会", block: "中国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 1, name: "平井卓也", party: "自由民主党", block: "四国", is_overlap: true, overlap_district: "香川1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Takuya_Hirai_20200131_%28cropped%29.jpg/330px-Takuya_Hirai_20200131_%28cropped%29.jpg" },
  { rank: 2, name: "瀬戸隆一", party: "自由民主党", block: "四国", is_overlap: true, overlap_district: "香川2区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Takakazu_Seto_20240329.jpg/330px-Takakazu_Seto_20240329.jpg" },
  { rank: 3, name: "山崎正恭", party: "中道改革連合", block: "四国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 4, name: "村上誠一郎", party: "自由民主党", block: "四国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Seiichir%C5%8D_Murakami%2C_Minister_for_Internal_Affairs_and_Communications.jpg" },
  { rank: 5, name: "飯泉嘉門", party: "国民民主党", block: "四国", is_overlap: true, overlap_district: "徳島2区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/%E5%BE%B3%E5%B3%B6%E7%9C%8C_%E7%9F%A5%E4%BA%8B_%E9%A3%AF%E6%B3%89%E5%98%89%E9%96%80.jpg/330px-%E5%BE%B3%E5%B3%B6%E7%9C%8C_%E7%9F%A5%E4%BA%8B_%E9%A3%AF%E6%B3%89%E5%98%89%E9%96%80.jpg" },
  { rank: 6, name: "中山展宏", party: "自由民主党", block: "四国", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/5/55/Nakayama_Norihiro_%282019%29.png" },
  { rank: 1, name: "小里泰弘", party: "自由民主党", block: "九州", is_overlap: true, overlap_district: "鹿児島3区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Yasuhiro_Ozato_20210914_%28cropped%29.jpg/330px-Yasuhiro_Ozato_20210914_%28cropped%29.jpg" },
  { rank: 2, name: "江藤拓", party: "自由民主党", block: "九州", is_overlap: true, overlap_district: "宮崎2区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Taku_Eto_20210311.jpg/330px-Taku_Eto_20210311.jpg" },
  { rank: 3, name: "浜地雅一", party: "中道改革連合", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 4, name: "武井俊輔", party: "自由民主党", block: "九州", is_overlap: true, overlap_district: "宮崎1区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Shunsuke_Takei_20220812.jpg" },
  { rank: 5, name: "三原朝利", party: "自由民主党", block: "九州", is_overlap: true, overlap_district: "福岡9区", recovery_rate: null, photo: null },
  { rank: 6, name: "吉田宣弘", party: "中道改革連合", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nobuhiro_Yoshida_20180820.jpg/330px-Nobuhiro_Yoshida_20180820.jpg" },
  { rank: 7, name: "木下敏之", party: "参政党", block: "九州", is_overlap: true, overlap_district: "福岡2区", recovery_rate: null, photo: null },
  { rank: 8, name: "許斐亮太郎", party: "国民民主党", block: "九州", is_overlap: true, overlap_district: "福岡4区", recovery_rate: null, photo: null },
  { rank: 9, name: "浅田真澄美", party: "自由民主党", block: "九州", is_overlap: true, overlap_district: "長崎1区", recovery_rate: null, photo: null },
  { rank: 10, name: "上野宏史", party: "自由民主党", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Hiroshi_Ueno.jpg" },
  { rank: 11, name: "金城泰邦", party: "中道改革連合", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/d/df/Yasukuni_Kinjou_2024.jpg" },
  { rank: 12, name: "古川あおい", party: "チームみらい", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 13, name: "村上智信", party: "日本維新の会", block: "九州", is_overlap: true, overlap_district: "福岡11区", recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/9/95/Tomonobu_Murakami_cropped_1_Ry%C5%8Dsei_Akazawa%2C_Fumitake_Fujita_and_Keishi_Abe_and_Tomonobu_Murakami_and_Rie_Sasaki_20251114_1.jpg" },
  { rank: 14, name: "保岡宏武", party: "自由民主党", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
  { rank: 15, name: "阿部弘樹", party: "自由民主党", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Hiroki_Abe_making_a_speech_in_front_of_Hakata_Station.jpg/330px-Hiroki_Abe_making_a_speech_in_front_of_Hakata_Station.jpg" },
  { rank: 16, name: "河野義博", party: "中道改革連合", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Kawano_Yoshihiro_%282019%29.png" },
  { rank: 17, name: "白坂亜紀", party: "自由民主党", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Aki_Shirasaka_2023-10-22_%28cropped%29.jpg/330px-Aki_Shirasaka_2023-10-22_%28cropped%29.jpg" },
  { rank: 18, name: "牧野俊一", party: "参政党", block: "九州", is_overlap: true, overlap_district: "鹿児島1区", recovery_rate: null, photo: null },
  { rank: 19, name: "近藤雅彦", party: "国民民主党", block: "九州", is_overlap: true, overlap_district: "福岡6区", recovery_rate: null, photo: null },
  { rank: 20, name: "河野正美", party: "自由民主党", block: "九州", is_overlap: false, overlap_district: null, recovery_rate: null, photo: null },
];

export const PROPORTIONAL_BLOCKS = [
  "北海道", "東北", "北関東", "南関東", "東京",
  "北陸信越", "東海", "近畿", "中国", "四国", "九州"
] as const;

export type ProportionalBlock = typeof PROPORTIONAL_BLOCKS[number];

// ブロック別議席数（第51回）
export const BLOCK_SEATS: Record<string, number> = {
  "北海道": 8,
  "東北": 12,
  "北関東": 19,
  "南関東": 22,
  "東京": 17,
  "北陸信越": 10,
  "東海": 21,
  "近畿": 28,
  "中国": 10,
  "四国": 6,
  "九州": 20,
};