/*
 * revival_data.ts — Proportional revival (比例復活) candidate data
 * Auto-generated from Wikipedia district pages.
 */

// Map of district_id -> list of candidate names who won via proportional revival
export const REVIVAL_CANDIDATES: Record<string, string[]> = {
  "aichi-01": ["熊田裕通"],
  "aichi-02": ["辻秀樹"],
  "aichi-05": ["渡辺藍理"],
  "aichi-07": ["鈴木淳司"],
  "aichi-11": ["藤澤忠盛"],
  "aichi-12": ["重徳和彦"],
  "aichi-15": ["関健一郎"],
  "aichi-16": ["福田徹"],
  "akita-03": ["御法川信英"],
  "chiba-01": ["田嶋要"],
  "chiba-04": ["工藤聖子"],
  "chiba-05": ["岡野純子", "小林修平"],
  "chiba-13": ["中谷めぐみ"],
  "chiba-14": ["長野春信"],
  "fukuoka-02": ["木下敏之"],
  "fukuoka-04": ["許斐亮太郎"],
  "fukuoka-06": ["近藤雅彦"],
  "fukuoka-09": ["三原朝利"],
  "fukuoka-11": ["村上智信"],
  "fukushima-01": ["金子恵美"],
  "gifu-02": ["野村美穂"],
  "gifu-03": ["伊藤恵介"],
  "gunma-04": ["青木ひとみ"],
  "hiroshima-04": ["鍋島勢理"],
  "hokkaido-01": ["臼木秀剛"],
  "hokkaido-09": ["山岡達丸"],
  "hokkaido-10": ["渡辺孝一"],
  "hyogo-01": ["一谷勇一郎"],
  "hyogo-03": ["向山好一"],
  "hyogo-06": ["市村浩一郎", "谷浩一郎"],
  "hyogo-07": ["三木圭恵"],
  "hyogo-11": ["住吉寛紀"],
  "hyogo-12": ["池畑浩太朗"],
  "ibaraki-05": ["鈴木拓海"],
  "ibaraki-07": ["永岡桂子"],
  "ishikawa-01": ["小竹凱", "川裕一郎"],
  "ishikawa-03": ["近藤和也"],
  "iwate-01": ["米内紘正"],
  "iwate-02": ["佐々木真琴"],
  "kagawa-01": ["平井卓也"],
  "kagawa-02": ["瀬戸隆一"],
  "kagoshima-01": ["牧野俊一"],
  "kagoshima-03": ["小里泰弘"],
  "kanagawa-04": ["早稲田夕季"],
  "kanagawa-09": ["笠浩史"],
  "kanagawa-10": ["金村龍那"],
  "kanagawa-16": ["後藤祐一"],
  "kanagawa-18": ["西岡義高", "横田光弘"],
  "kanagawa-19": ["深作ヘスス"],
  "kyoto-02": ["藤田洋司"],
  "kyoto-03": ["繁本護"],
  "miyagi-02": ["和田政宗"],
  "miyazaki-01": ["武井俊輔"],
  "miyazaki-02": ["江藤拓"],
  "nagano-01": ["若狹清史"],
  "nagasaki-01": ["浅田真澄美"],
  "nara-03": ["原山大亮"],
  "niigata-01": ["西村智奈美"],
  "niigata-02": ["菊田真紀子"],
  "osaka-04": ["中山泰秀"],
  "osaka-07": ["渡嘉敷奈緒美", "石川勝"],
  "osaka-08": ["高麗啓一郎"],
  "osaka-09": ["東田淳平"],
  "osaka-13": ["宗清皇一"],
  "osaka-15": ["島田智明"],
  "osaka-19": ["伊東信久"],
  "saitama-06": ["大島敦"],
  "saitama-13": ["橋本幹彦"],
  "saitama-14": ["鈴木義弘"],
  "shiga-01": ["斎藤アレックス", "河井昭成"],
  "shizuoka-04": ["田中健"],
  "tochigi-01": ["柏倉祐司"],
  "tochigi-03": ["簗和生"],
  "tokushima-02": ["飯泉嘉門"],
  "tokyo-01": ["吉川里奈"],
  "tokyo-02": ["土橋章宏"],
  "tokyo-04": ["井戸正枝"],
  "tokyo-06": ["落合貴之"],
  "tokyo-07": ["峰島侑也"],
  "tokyo-11": ["高沢一基"],
  "tokyo-12": ["阿部司"],
  "tokyo-13": ["森洋介"],
  "tokyo-22": ["鈴木美香"],
  "tokyo-26": ["宇佐美登"],
  "tokyo-27": ["長妻昭"],
  "yamaguchi-03": ["島村薫"],
};

// Helper to check if a candidate got proportional revival
export function isRevivalCandidate(districtId: string, candidateName: string): boolean {
  const candidates = REVIVAL_CANDIDATES[districtId];
  if (!candidates) return false;
  return candidates.includes(candidateName);
}
